src/RequestParser.php

More info in the issue https://github.com/reactphp/http/issues/44

Fixes reactphp/http#44 - postfields parsing without urldecode

---

README.md
examples/01-hello-world.php

Let's make it easier for newcomers to get started :tada:

Add functional example to ease getting started

---

composer.json
src/Server.php
tests/ServerTest.php
tests/TestCase.php

Do not emit empty data events

---

composer.json

Fix version clash of https://github.com/reactphp/http/issues/111

Upgrade ringcentral/psr7 to 1.2

---

README.md
composer.json
examples/01-hello-world.php
src/Server.php
tests/ServerTest.php
tests/SocketServerStub.php

Filing this as a WIP until the v0.5 release has actually been tagged and released.

Update Socket component to v0.5

---

composer.json

Refs https://github.com/reactphp/socket/issues/75

Forward compatibility with upcoming Socket v0.6 and v0.7

---

src/RequestHeaderParser.php
tests/ServerTest.php

See https://tools.ietf.org/html/rfc7230#section-5.3.4
Builds on top of #152

Support asterisk-form request target for OPTIONS method

---

README.md
composer.json
examples/21-connect-proxy.php
src/RequestHeaderParser.php
src/Server.php
tests/ServerTest.php

See https://tools.ietf.org/html/rfc7231#section-4.3.6 and https://tools.ietf.org/html/rfc7230#section-5.3.3.
Builds on top of #152, #156 and #157

Support CONNECT method

---

composer.json
examples/21-connect-proxy.php

Update SocketClient to v0.7 to simplify CONNECT example

---

tests/SocketServerStub.php

Fix tests to support new Socket v0.6 and up

---

composer.json
examples/21-connect-proxy.php

Builds on top of #161 which builds on top of #158

Replace deprecated SocketClient with new Socket component to simplify CONNECT example

---

examples/01-hello-world.php
examples/02-count-visitors.php
examples/03-client-ip.php
examples/04-query-parameter.php
examples/05-cookie-handling.php
examples/06-sleep.php
examples/07-error-handling.php
examples/08-stream-response.php
examples/09-stream-request.php
examples/11-hello-world-https.php
examples/21-http-proxy.php
examples/22-connect-proxy.php
examples/31-upgrade-echo.php
examples/32-upgrade-chat.php
examples/99-benchmark-download.php

This is a simple follow-up fix for #183, in particular for the changes in https://github.com/reactphp/socket/pull/98

Fix reporting listening addresses in examples

---

examples/32-upgrade-chat.php
src/RequestHeaderParser.php
src/Server.php
tests/FunctionalServerTest.php
tests/Middleware/RequestBodyParserMiddlewareTest.php
tests/ServerTest.php

Minor code tweaks:
- resolved a greedy regex in an example
- got rid of unnecessary method calls when parsing requests
- some dead code fragments dropped

SCA with Php Inspections (EA Extended)

---

.travis.yml
tests/benchmark-middleware-runner.php

I've been working on some performance improvements for the middleware runner. In order to test those I've written this benchmark.

Middleware runner benchmark

---

tests/MiddlewareRunnerTest.php

Ref https://github.com/reactphp/http/pull/236#issuecomment-335716226

Add MiddlewareRunner test ensuring multiple runs always invoke all middleware

---

tests/MiddlewareRunnerTest.php

Extends test added in #238 testing also handlers which return a rejected promise.

Extend test to ensure next handler can be run more than once when handler rejects

---

src/Io/MultipartParser.php
tests/Io/MultipartParserTest.php

Builds on top of #261 and #252

Report error if no file is selected for upload (UPLOAD_ERR_NO_FILE)

---

tests/Io/HttpBodyStreamTest.php
tests/Io/MultipartParserTest.php
tests/Io/ServerRequestTest.php
tests/StreamingServerTest.php

I've refactored some tests with [`assertNull`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertNull) method.

Refactoring tests

---

src/StreamingServer.php

With `Server` marked as final, `StreamingServer` should be marked final as well

Mark StreamingServer final

---

tests/ServerTest.php

Refs https://github.com/reactphp/event-loop/pull/138

Fix test suite forward compatibility with upcoming EventLoop releases

---

src/Middleware/LimitConcurrentRequestsMiddleware.php
tests/Middleware/LimitConcurrentRequestsMiddlewareTest.php

This PR avoids queuing and immediately dequeuing when concurrency is below limit. This also avoid wrapping the return value from the request handler in another promise. The request handler will either return a promise or a value that can be consumed directly. When running example 99 with included benchmarking instructions, this change improves performance from ~2500 req/s to ~2900 req/s on my local machine. With #294 also applied locally, this change improves performance to ~3100 req/s on my local machine.
Builds on top of #291 and #292 and #293
Refs #294

Improve performance by avoiding unneeded promise wrapping when concurrency is below limit

---

README.md
src/StreamingServer.php
tests/StreamingServerTest.php

Assign Content-Length response header automatically only when size is known

---

LICENSE

Added the full core team in order of joining the team

Add full core team to the license

---

README.md

Just some random broken link :)

Minor documentation fix for broken anchor link
